Repository nromanen/ua-1322-python-fundamentals, pull requests merged in 2025-01, with the labels that each got.

#29 add 3d lection tasks
  HW3/FilippovOleksandr/Task_1.py
  HW3/FilippovOleksandr/Task_2.py
  HW3/FilippovOleksandr/Task_3.py
Labels: Lection_3

#42 HW5 Filippov Oleksandr
  HW5/FilippovOleksandr.py
Labels: lection_5

#38 HW6 task_1 && task_2
  HW6/Task_1.py
  HW6/Task_2.py
Labels: lection_6

#59 Gnatenko HW5
  HW5/IrynaGnatenko/Gnatenko_homework_5.1.py
  HW5/IrynaGnatenko/Gnatenko_homework_5.2.py
  HW5/IrynaGnatenko/Gnatenko_homework_5.3.py
Labels: lecture_5

#70 Add HW6
  HW6/IrynaGnatenko/Gnatenko_homework_6.1.py
  HW6/IrynaGnatenko/Gnatenko_homework_6.2.py
Labels: lecture_6

#56 HW7 Filippov Oleksandr
  HW7/Filippov_Oleksandr/task_1.py
  HW7/Filippov_Oleksandr/task_2.py
  HW7/Filippov_Oleksandr/task_3.py
Labels: lecture_7
